### ISSUE TITLE
There is no way to use PNG transparency to generate Interlaced Masks

### ISSUE THREAD

**Issue by lronaldo** [AugustoRuiz/Img2CPC#3]
Interlaced Masks option requires a transparent color from the palette to generate the masks. However, this shouldn't be required, as interlaced masks do not depend on a palette color, as mask tables do. I suggest generating interlaced masks out of 3 possibilities:
- Actual transparency values from the original image (such as PNG transparency)
- An specific RGB colour in the original image (that could be different from all Amstrad CPC colours, for instance)
- A palette index colour, like now (just to let users pick this option if they wanted, even if it is not useful in general)

**Comment by AugustoRuiz** [comment]
Solved with commit:

https://github.com/AugustoRuiz/Img2CPC/commit/347f905a40524eb90b943fedc3bce68760cc32ab
