### ISSUE TITLE
Doesn't compile from a clean clone

### ISSUE THREAD

**Issue by duncan-bayne** [AugustoRuiz/Img2CPC#4]
```
➜  Img2CPC git:(master) gmake -f Makefile.others 
g++ -std=c++11 -O3 -Werror -Wall -fsigned-char -o obj/Palette.o -c -Iinclude src/Palette.cc
Assembler messages:
Fatal error: can't create obj/Palette.o: No such file or directory
gmake: *** [Makefile.others:28: obj/Palette.o] Error 1
```

* FreeBSD 11.1-RELEASE GENERIC amd64
* gcc (FreeBSD Ports Collection) 6.4.0
* GNU Make 4.2.1

I'll submit a PR for this shortly, as part of my work to get this tool working on FreeBSD.

**Comment by duncan-bayne** [comment]
Haven't had an opportunity to get this going on FreeBSD in a while.  Closing for now.

**Comment by AugustoRuiz** [comment]
The error says that it cannot create the directory where the .o file is
created. The folder name should be obj. I guess you'll have the same
problem when creating the final binary (in this case the directory is bin).

The makefile tries to do so by calling mkdir -p obj and mkdir -p bin.

Could you try creating the directory using the shell, and running make
again?

Kind regards,



Augusto.
